services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      
      ethereum_rpc_url: ${ETHEREUM_RPC_URL}
      # ethereum: 'sepolia:${ETHEREUM_RPC_URL}'
      GRAPH_LOG: info
      ETHEREUM_POLLING_INTERVAL: 5000
      GRAPH_ETHEREUM_BLOCK_BATCH_SIZE: 1
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: 10
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: 10
    volumes:
      - ./data:/data

  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
